### PR TITLE
Make map[int] validate correctly in schema

### LINKED ISSUE #93: map[int] could do better
Hey, awesome library, thanks a lot

I was using it to validate json and discovered that I could use random strings for map[int] types and still validate correctly, but then fail on unmarshal

So after plaing with the schema specs a little I figured that it could be fixed using something like this in reflect.go:

```
	case reflect.Map:
		var i int
		if t.Key() == reflect.TypeOf(i) {
			rt := &Type{
				Type: "object",
				PatternProperties: map[string]*Type{
					"^[0-9]+$": r.reflectTypeToSchema(definitions, t.Elem()),
				},
				AdditionalProperties: []byte("false"),
			}
			return rt
		}
		rt := &Type{
			Type: "object",
			PatternProperties: map[string]*Type{
				".*": r.reflectTypeToSchema(definitions, t.Elem()),
			},
		}
		delete(rt.PatternProperties, "additionalProperties")
		return rt
```

What do you think ? uint and other int types can not be used as string types in go as far as I know, so this should be an ok solution.

Should I prep a PR ? what do you think ?

Greetings

### PR DESCRIPTION
**Pull request by s00500**
Adds a pattern to correctly validate the map keys in case it is a map[int] to integery
Closes #93

### CODE REVIEW

File: reflect.go [hunk 1]
```diff
@@ -257,6 +256,17 @@ func (r *Reflector) reflectTypeToSchema(definitions Definitions, t reflect.Type)
 		}
 
 	case reflect.Map:
+		var i int
+		if t.Key() == reflect.TypeOf(i) {
```
Comment (alecthomas) [inline reflect.go:260]: To be consistent this should be extended to cover all of the integer numeric types, and probably floats as well (though the pattern would be quite a bit more complex for floats).

A more convenient way to do this than comparing types is to compare the kind:

```
switch t.Key().Kind() {
  case reflect.Int, reflect.Int8, reflect.Int16, ...
  case reflect.Float32, reflect.Float64:
}

**Review by alecthomas — CHANGES_REQUESTED** [review]
.

**Comment by s00500** [comment]
Sorry, was pretty busy yesterday, yes the switch is much more pretty, I added the changes now :-)

File: reflect.go [hunk 2]
```diff
@@ -257,6 +256,27 @@ func (r *Reflector) reflectTypeToSchema(definitions Definitions, t reflect.Type)
...
+					"^[0-9]+$": r.reflectTypeToSchema(definitions, t.Elem()),
+				},
+				AdditionalProperties: []byte("false"),
+			}
+			return rt
+		case reflect.Float32, reflect.Float64:
+			rt := &Type{
+				Type: "object",
+				PatternProperties: map[string]*Type{
+					"^[-+]?[0-9]*\\.?[0-9]+$": r.reflectTypeToSchema(definitions, t.Elem()),
```
Comment (alecthomas) [inline reflect.go:273]: Unfortunately a float regex is much more complex than this, and hard to get right. For example this doesn't support exponents.

 It might be simpler just to not worry about floats.

**Review by alecthomas — CHANGES_REQUESTED** [review]

File: reflect.go (hunk 2 above)
Comment (s00500) [reply reflect.go:273]: This one would: ^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$

What do you think ?

File: reflect.go [hunk 3]
```diff
@@ -270,7 +270,7 @@ func (r *Reflector) reflectTypeToSchema(definitions Definitions, t reflect.Type)
 			rt := &Type{
 				Type: "object",
 				PatternProperties: map[string]*Type{
-					"^[-+]?[0-9]*\\.?[0-9]+$": r.reflectTypeToSchema(definitions, t.Elem()),
```
Comment (alecthomas) [inline reflect.go]: I think it would be better to remove it for now, because unless we can be 100% certain that it allows all JS float formats, this could break downstream packages.

**Review by alecthomas — APPROVED** [review]

**Comment by alecthomas** [comment]
Awesome thanks!

**Comment by s00500** [comment]
Just for reference: I used regex from here: https://www.regular-expressions.info/floatingpoint.html 

Thanks for the great library =D
